### ISSUE TITLE
Refine Create Resource to Incorporate Product.py

### ISSUE THREAD

**Issue by cfnyu** [devopsdelta/recommendations#11]
**As a** Service Provider
**I need** a way to create a recommendation
**So that** other service can get recommendations for products

**Assumptions:** 
* This will use the POST method
* This will not be persisted

**Acceptance Criteria:**
```
If I browse to /recommendations/{product_id}
A recommendation will be created and a location will be stored in the Location field of the request.
```

**Comment by sfloam** [comment]
Modified this issue since we agreed last night that this would be an enhancement feature during the meeting. Since Christian's server file ended up containing a primitive Create, we decided to convert this into a refinement issue. It should be held over until Sprint 2.

**Comment by sfloam** [comment]
We will be creating new issue to refactor product.py instead. This will be closed.
