### ISSUE TITLE
Refine Read a Resource

### ISSUE THREAD

**Issue by cfnyu** [devopsdelta/recommendations#12]
**As a** User
**I need** a way to get a previous generated recommendation
**So that** I can see related products

**Assumptions:** 
* This will use the GET method
* This will not be persisted

**Acceptance Criteria:**
```
If I browse to `/recommendations/{product_id}`
A list of recommended products will be returned.
```

**Comment by sfloam** [comment]
@cfnyu is there a way to connect @Harivadhana 's issues here to your server PR?

**Comment by cfnyu** [comment]
Absorbed by Refractor models.py #56
