### ISSUE TITLE
Setup Delete Resource

### ISSUE THREAD

**Issue by cfnyu** [devopsdelta/recommendations#15]
**As a** user
**I need** a way to delete an existing recommendation
**So that** the recommendation no longer exists

**Assumptions:** 
* This will use the DELETE method
* This will not be persisted

**Acceptance Criteria:**

If I browse to `/recommendations/{product_id}`
Then a 200 will be returned for a successful delete and a 404 will be returned if the recommendation doesn't already exists

**Comment by sfloam** [comment]
This should return a string: "You have deleted {item id}"
str(variable) + "this string"

**Comment by bk1713** [comment]
@sfloam Delete being idempotent, I think we shouldn't return a 404. What do you think?
http://harikt.com/blog/2013/11/01/rest-is-delete-idempotent/

**Comment by sfloam** [comment]
Please only assign one issue at a time.

**Comment by cfnyu** [comment]
Absorbed by Refractor models.py #56
