### ISSUE TITLE
Update the Vagrantfile to include LAMP

### ISSUE THREAD

**Issue by cfnyu** [devopsdelta/recommendations#3]
**As a** Developer
**I need** my local development environment to include LAMP 
**So that** I can test the service locally with no internet connection

**Assumptions:** 
* The Vagrantfile will add the LAMP stack while building the VM
* We can use a LAMP docker image

**Acceptance Criteria:**
```
When I start the Vagrant vm with `vagrant up && vagrant ssh`
And browse to http://localhost
I should see a test site running
```

**Comment by cfnyu** [comment]
Here might be a good starting point for getting this setup: 

https://github.com/czettnersandor/vagrant-docker-lamp

This project has more than we need but could be of good use.

**Comment by bk1713** [comment]
Unnecessary as we are using Bluemix.
