### ISSUE TITLE
Scaffold a RESTFul API

### ISSUE THREAD

**Issue by cfnyu** [devopsdelta/recommendations#5]
**As a** Developer
**I need** a starting point for the service
**So that** when can ensure all of the infrastructure has been created and setup properly before I begin developing the actual APIs

**Assumptions:** 
* Nothing will be persisted

**Acceptance Criteria:**
```
When I browse to http://localhost
I should see a list of all the resources available from the service
```

**Comment by sfloam** [comment]
Note: we are not completing the service. Just setting it up.

**Comment by sfloam** [comment]
Just to confirm, @cfnyu and @Harivadhana, this is ready for review? Or is it in progress?

**Comment by cfnyu** [comment]
So this is up for review, and discussion.

**Comment by sfloam** [comment]
@Harivadhana can I close this? I believe server.py is handling this. Just want to do some quick grooming.

**Comment by sfloam** [comment]
Closed because we went with Christian's enhancement/skeleton model and server python api.
