### ISSUE TITLE
Create a UI

### ISSUE THREAD

**Issue by sfloam** [devopsdelta/recommendations#51]
**As a** developer
**I need** to create a User Interface
**So that** I can capture user data from a website

**Assumptions:** 
- [x] I have a working model and controller with Create, Read, Update, Delete, List, Query, Action functionality
- [x] My application supports behave and Selenium

**Acceptance Criteria:**
```
Given A functional User Interface
When A user interacts with my UI 
Then I should be able implement the Create, Read, Update, Delete, List, Query, Action functionality on existing and/or newly provided data
And I can test the User Interface with behave using Selenium to ensure that the User Interface meets the business needs of the application
```

**Comment by cfnyu** [comment]
This issue is too broad and we do not want to convert this to an epic
