### ISSUE TITLE
Modify Vagrantfile to include Cloud Foundry CLI

### ISSUE THREAD

**Issue by cfnyu** [devopsdelta/recommendations#55]
**As a** Developer
**I need** to modify the Vagrantfile
**So that** the Bluemix CLI is apart of the Development environment for all Developers

**Assumptions:** 
* Use the Bluemix CLI (which includes Cloud Foundry CLI)

**Acceptance Criteria:**
```
Given the Bluemix CLI is installed
When I execute `vagrant up`
And I execute `bx cf --version` in the command line 
Then I should see the installed version of Cloud Foundry
```

**Comment by sfloam** [comment]
Update to include organization information in acceptance
