### ISSUE TITLE
Restructuring the recommendation service

### ISSUE THREAD

**Issue by cfnyu** [devopsdelta/recommendations#7]
**As a** User
**I need** a way to ask for recommendations
**So that** I can show a customer other products they might be interested in purchasing

**Assumptions:** 
* Add a URL of /recommendations
* The URL should allow for a query string parameter `r` to specify how many recommendations should be returned. Three recommendations can be the default
* URL should return a specified number of recommendations

**Acceptance Criteria:**
When I call the URL /recommendations
It should return a JSON object with the recommendations based on some product
```
{
   Recommendations: []
}
```

**Comment by sfloam** [comment]
Isn't this really an epic?

**Comment by cfnyu** [comment]
No longer needed because other user stories have completed the same tasks.
