### ISSUE TITLE
Update Model Changes

### ISSUE THREAD

**Issue by Harivadhana** [devopsdelta/recommendations#76]
**As a** developer
**I need** to denormalize Recommendation and Recommendation Details 
**So that** all data is stored in one table and CRUD operation complexities are removed

**Assumptions:** 
* New table name will be Recommendation
* Remove constraint on Recommendation to allow multiple Product Id and Type Id combo
* Delete the RecommendationDetail object
* Will require refactor on exiting unit test for both models and server

**Acceptance Criteria:**
```
Given an updated model
When I look at the Postgres Schema
Then I should only see two tables: recommendation_type and recommendation
```

**Comment by sfloam** [comment]
We should come back to this one and maybe clean up the language of the user story before we kill the Sprint.
